2019-10-21 22:00:53,876 p=817 u=shiyanlou |   [WARNING]: Unable to parse /home/shiyanlou/ansibl_ui/scripts/inventory as an inventory source

2019-10-21 22:00:53,876 p=817 u=shiyanlou |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-10-21 22:00:53,908 p=817 u=shiyanlou |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

2019-10-21 22:00:55,802 p=817 u=shiyanlou |  localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2019-10-21 22:03:59,640 p=860 u=shiyanlou |  ERROR! Missing required action
2019-10-21 22:04:17,620 p=869 u=shiyanlou |  Encryption successful
2019-10-21 22:04:37,808 p=886 u=shiyanlou |   [WARNING]: Unable to parse /home/shiyanlou/ansibl_ui/scripts/inventory as an inventory source

2019-10-21 22:04:37,808 p=886 u=shiyanlou |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-10-21 22:04:37,825 p=886 u=shiyanlou |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

2019-10-21 22:04:37,855 p=886 u=shiyanlou |  ERROR! Attempting to decrypt but no vault secrets found
2019-10-21 22:05:30,344 p=896 u=shiyanlou |   [WARNING]: Unable to parse /home/shiyanlou/ansibl_ui/scripts/inventory as an inventory source

2019-10-21 22:05:30,345 p=896 u=shiyanlou |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-10-21 22:05:30,365 p=896 u=shiyanlou |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

2019-10-21 22:05:31,636 p=896 u=shiyanlou |   [WARNING]: Could not match supplied host pattern, ignoring: locahost

2019-10-21 22:05:31,646 p=896 u=shiyanlou |  PLAY [locahost] ***************************************************************************************************
2019-10-21 22:05:31,646 p=896 u=shiyanlou |  skipping: no hosts matched
2019-10-21 22:05:31,646 p=896 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-21 22:06:13,162 p=911 u=shiyanlou |  Decryption successful
2019-10-21 22:06:37,122 p=930 u=shiyanlou |   [WARNING]: Error in vault password prompt (default): Passwords do not match

2019-10-21 22:06:37,123 p=930 u=shiyanlou |  ERROR! Passwords do not match
2019-10-21 22:06:44,544 p=939 u=shiyanlou |  Encryption successful
2019-10-21 22:06:53,041 p=949 u=shiyanlou |   [WARNING]: Unable to parse /home/shiyanlou/ansibl_ui/scripts/inventory as an inventory source

2019-10-21 22:06:53,041 p=949 u=shiyanlou |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-10-21 22:06:53,060 p=949 u=shiyanlou |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

2019-10-21 22:06:54,224 p=949 u=shiyanlou |  PLAY [localhost] **************************************************************************************************
2019-10-21 22:06:54,244 p=949 u=shiyanlou |  TASK [Gathering Facts] ********************************************************************************************
2019-10-21 22:07:03,351 p=949 u=shiyanlou |  ok: [localhost]
2019-10-21 22:07:03,411 p=949 u=shiyanlou |  TASK [Ping] *******************************************************************************************************
2019-10-21 22:07:04,266 p=949 u=shiyanlou |  ok: [localhost]
2019-10-21 22:07:04,276 p=949 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-21 22:07:04,276 p=949 u=shiyanlou |  localhost                  : ok=2    changed=0    unreachable=0    failed=0   
2019-10-21 22:07:12,176 p=1021 u=shiyanlou |  Decryption successful
2019-10-21 22:08:12,957 p=1030 u=shiyanlou |   [ERROR]: User interrupted execution

2019-10-21 22:08:46,862 p=1046 u=shiyanlou |   [WARNING]: Unable to parse /home/shiyanlou/ansibl_ui/scripts/inventory as an inventory source

2019-10-21 22:08:46,862 p=1046 u=shiyanlou |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-10-21 22:08:46,881 p=1046 u=shiyanlou |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

2019-10-21 22:08:48,001 p=1046 u=shiyanlou |  PLAY [localhost] **************************************************************************************************
2019-10-21 22:08:48,062 p=1046 u=shiyanlou |  TASK [Ping] *******************************************************************************************************
2019-10-21 22:08:48,772 p=1046 u=shiyanlou |  ok: [localhost]
2019-10-21 22:08:48,781 p=1046 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-21 22:08:48,781 p=1046 u=shiyanlou |  localhost                  : ok=1    changed=0    unreachable=0    failed=0   
2019-10-21 22:09:54,242 p=1079 u=shiyanlou |   [WARNING]: Unable to parse /home/shiyanlou/ansibl_ui/scripts/inventory as an inventory source

2019-10-21 22:09:54,242 p=1079 u=shiyanlou |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-10-21 22:09:54,261 p=1079 u=shiyanlou |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

2019-10-21 22:09:56,247 p=1079 u=shiyanlou |  localhost | CHANGED | rc=0 >>
/tmp

2019-10-21 22:14:15,021 p=1130 u=shiyanlou |   [WARNING]: Unable to parse /home/shiyanlou/ansibl_ui/scripts/inventory as an inventory source

2019-10-21 22:14:15,021 p=1130 u=shiyanlou |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-10-21 22:14:15,041 p=1130 u=shiyanlou |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

2019-10-21 22:14:16,166 p=1130 u=shiyanlou |  PLAY [localhost] **************************************************************************************************
2019-10-21 22:14:16,230 p=1130 u=shiyanlou |  TASK [测试 shell] ***************************************************************************************************
2019-10-21 22:14:17,004 p=1130 u=shiyanlou |  changed: [localhost]
2019-10-21 22:14:17,015 p=1130 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-21 22:14:17,016 p=1130 u=shiyanlou |  localhost                  : ok=1    changed=1    unreachable=0    failed=0   
2019-10-21 22:17:05,496 p=1211 u=shiyanlou |  ERROR! Missing target hosts
2019-10-21 22:17:16,956 p=1220 u=shiyanlou |   [WARNING]: Unable to parse /home/shiyanlou/ansibl_ui/scripts/inventory as an inventory source

2019-10-21 22:17:16,957 p=1220 u=shiyanlou |   [WARNING]: No inventory was parsed, only implicit localhost is available

2019-10-21 22:17:16,980 p=1220 u=shiyanlou |   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

2019-10-21 22:17:19,646 p=1220 u=shiyanlou |  localhost | CHANGED => {
    "changed": true,
    "checksum": "cc6297cf16ddfd8132b508fa08a147cf1eabec64",
    "dest": "/tmp/hosts",
    "gid": 1000,
    "group": "shiyanlou",
    "md5sum": "7437562c110edefa547ccea3fd25937f",
    "mode": "0644",
    "owner": "shiyanlou",
    "size": 302,
    "src": "/home/shiyanlou/.ansible/tmp/ansible-tmp-1571667438.2093432-92897113733942/source",
    "state": "file",
    "uid": 1000
}
2019-10-22 22:14:08,389 p=3042 u=shiyanlou |    hosts (8):
2019-10-22 22:14:08,400 p=3042 u=shiyanlou |      web1
2019-10-22 22:14:08,400 p=3042 u=shiyanlou |      192.168.1.1
2019-10-22 22:14:08,400 p=3042 u=shiyanlou |      192.168.1.2
2019-10-22 22:14:08,400 p=3042 u=shiyanlou |      db-a.product
2019-10-22 22:14:08,400 p=3042 u=shiyanlou |      db-b.product
2019-10-22 22:14:08,400 p=3042 u=shiyanlou |      db-c.product
2019-10-22 22:14:08,400 p=3042 u=shiyanlou |      db-d.product
2019-10-22 22:14:08,401 p=3042 u=shiyanlou |      db-e.product
2019-10-22 22:16:31,043 p=3051 u=shiyanlou |  localhost | SUCCESS => {
    "msg": ""
}
2019-10-22 22:17:03,807 p=3070 u=shiyanlou |  localhost | SUCCESS => {
    "msg": ""
}
2019-10-22 22:17:20,123 p=3084 u=shiyanlou |  localhost | SUCCESS => {
    "msg": "I am shiyanlou"
}
2019-10-23 20:57:42,352 p=1420 u=shiyanlou |  	to retry, use: --limit @/home/shiyanlou/.ansible-retry/test_debug.retry

2019-10-23 21:28:16,683 p=1883 u=shiyanlou |  localhost | CHANGED | rc=0 >>
shiyanlou

2019-10-23 21:28:16,701 p=1883 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds
2019-10-23 21:30:46,404 p=1950 u=shiyanlou |  PLAY [localhost] *************************************************************************************************************************
2019-10-23 21:30:46,501 p=1950 u=shiyanlou |  TASK [检查redis-server文件是否存在] **************************************************************************************************************
2019-10-23 21:30:47,652 p=1950 u=shiyanlou |  ok: [localhost]
2019-10-23 21:30:47,731 p=1950 u=shiyanlou |  TASK [安装redis] ***************************************************************************************************************************
2019-10-23 21:30:47,792 p=1950 u=shiyanlou |  skipping: [localhost]
2019-10-23 21:30:47,871 p=1950 u=shiyanlou |  TASK [Redis配置文件] *************************************************************************************************************************
2019-10-23 21:30:49,219 p=1950 u=shiyanlou |  ok: [localhost]
2019-10-23 21:30:49,288 p=1950 u=shiyanlou |  TASK [检测Redis服务是否启动] *********************************************************************************************************************
2019-10-23 21:30:50,047 p=1950 u=shiyanlou |  fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/bin/redis-cli quit", "delta": "0:00:00.091687", "end": "2019-10-23 21:30:49.994893", "msg": "non-zero return code", "rc": 1, "start": "2019-10-23 21:30:49.903206", "stderr": "Could not connect to Redis at 127.0.0.1:6379: Connection refused", "stderr_lines": ["Could not connect to Redis at 127.0.0.1:6379: Connection refused"], "stdout": "", "stdout_lines": []}
2019-10-23 21:30:50,048 p=1950 u=shiyanlou |  ...ignoring
2019-10-23 21:30:50,108 p=1950 u=shiyanlou |  TASK [启动Redis服务，如果redis 未启动] *************************************************************************************************************
2019-10-23 21:30:50,672 p=1950 u=shiyanlou |  changed: [localhost]
2019-10-23 21:30:50,681 p=1950 u=shiyanlou |  PLAY RECAP *******************************************************************************************************************************
2019-10-23 21:30:50,681 p=1950 u=shiyanlou |  localhost                  : ok=4    changed=2    unreachable=0    failed=0   
2019-10-23 21:30:50,681 p=1950 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 4 seconds
2019-10-23 21:37:58,013 p=2192 u=shiyanlou |  localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2019-10-23 21:37:58,026 p=2192 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
2019-10-23 21:39:24,703 p=2238 u=shiyanlou |  localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2019-10-23 21:39:24,718 p=2238 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
2019-10-23 21:41:12,341 p=2372 u=shiyanlou |  localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2019-10-23 21:41:12,351 p=2372 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 1 seconds
2019-10-23 21:41:31,048 p=2409 u=shiyanlou |  PLAY [localhost] *************************************************************************************************************************
2019-10-23 21:41:31,130 p=2409 u=shiyanlou |  TASK [Debug] *****************************************************************************************************************************
2019-10-23 21:41:31,232 p=2409 u=shiyanlou |  ok: [localhost] => {
    "msg": "Hello"
}
2019-10-23 21:41:31,246 p=2409 u=shiyanlou |  PLAY RECAP *******************************************************************************************************************************
2019-10-23 21:41:31,246 p=2409 u=shiyanlou |  localhost                  : ok=1    changed=0    unreachable=0    failed=0   
2019-10-23 21:41:31,246 p=2409 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
2019-10-23 21:41:42,431 p=2427 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
2019-10-23 22:02:37,871 p=764 u=shiyanlou |  PLAY [localhost] *************************************************************************************************************************
2019-10-23 22:02:37,969 p=764 u=shiyanlou |  TASK [检查redis-server文件是否存在] **************************************************************************************************************
2019-10-23 22:02:39,383 p=764 u=shiyanlou |  ok: [localhost]
2019-10-23 22:02:39,384 p=764 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at 0x7faf7b8bd8d0>): Error 111
connecting to 127.0.0.1:6379. Connection refused.

2019-10-23 22:02:39,506 p=764 u=shiyanlou |  TASK [安装redis] ***************************************************************************************************************************
2019-10-23 22:02:39,552 p=764 u=shiyanlou |  skipping: [localhost]
2019-10-23 22:02:39,553 p=764 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_skipped) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at 0x7faf7b8bd8d0>): name 'host' is
not defined

2019-10-23 22:02:39,622 p=764 u=shiyanlou |  TASK [Redis配置文件] *************************************************************************************************************************
2019-10-23 22:02:41,007 p=764 u=shiyanlou |  ok: [localhost]
2019-10-23 22:02:41,082 p=764 u=shiyanlou |  TASK [检测Redis服务是否启动] *********************************************************************************************************************
2019-10-23 22:02:41,808 p=764 u=shiyanlou |  fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/bin/redis-cli quit", "delta": "0:00:00.013781", "end": "2019-10-23 22:02:41.756997", "msg": "non-zero return code", "rc": 1, "start": "2019-10-23 22:02:41.743216", "stderr": "Could not connect to Redis at 127.0.0.1:6379: Connection refused", "stderr_lines": ["Could not connect to Redis at 127.0.0.1:6379: Connection refused"], "stdout": "", "stdout_lines": []}
2019-10-23 22:02:41,808 p=764 u=shiyanlou |  ...ignoring
2019-10-23 22:02:41,809 p=764 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at 0x7faf7b8bd8d0>): Error 111
connecting to 127.0.0.1:6379. Connection refused.

2019-10-23 22:02:41,890 p=764 u=shiyanlou |  TASK [启动Redis服务，如果redis 未启动] *************************************************************************************************************
2019-10-23 22:02:42,348 p=764 u=shiyanlou |  changed: [localhost]
2019-10-23 22:02:42,365 p=764 u=shiyanlou |  PLAY RECAP *******************************************************************************************************************************
2019-10-23 22:02:42,366 p=764 u=shiyanlou |  localhost                  : ok=4    changed=2    unreachable=0    failed=0   
2019-10-23 22:02:42,366 p=764 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 4 seconds
2019-10-23 22:09:36,844 p=992 u=shiyanlou |  ERROR! Unexpected Exception, this is probably a bug: __init__() missing 1 required positional argument: 'id'
2019-10-23 22:09:36,844 p=992 u=shiyanlou |  to see the full traceback, use -vvv
2019-10-23 22:09:36,860 p=992 u=shiyanlou |  the full traceback was:

Traceback (most recent call last):
  File "/home/shiyanlou/py3/bin/ansible", line 118, in <module>
    exit_code = cli.run()
  File "/home/shiyanlou/py3/lib/python3.5/site-packages/ansible/cli/adhoc.py", line 179, in run
    result = self._tqm.run(play)
  File "/home/shiyanlou/py3/lib/python3.5/site-packages/ansible/executor/task_queue_manager.py", line 230, in run
    self.load_callbacks()
  File "/home/shiyanlou/py3/lib/python3.5/site-packages/ansible/executor/task_queue_manager.py", line 209, in load_callbacks
    callback_obj = callback_plugin()
TypeError: __init__() missing 1 required positional argument: 'id'

2019-10-23 22:11:38,148 p=1023 u=shiyanlou |  localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2019-10-23 22:11:38,148 p=1023 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at 0x7f533f0c01d0>): 'str' object has
no attribute 'name'

2019-10-23 22:11:38,161 p=1023 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
2019-10-23 22:14:33,928 p=1069 u=shiyanlou |  localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
2019-10-23 22:14:33,946 p=1069 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
2019-10-23 22:29:51,391 p=1287 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
2019-10-24 03:16:31,945 p=2253 u=shiyanlou |  PLAY [localhost] ***************************************************************
2019-10-24 03:16:32,022 p=2253 u=shiyanlou |  TASK [shell] *******************************************************************
2019-10-24 03:16:32,795 p=2253 u=shiyanlou |  changed: [localhost]
2019-10-24 03:16:32,796 p=2253 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (<ansible
.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackMo
dule object at 0x7f32451cfa90>): Error 111 connecting to 127.0.0.1:6379.
Connection refused.

2019-10-24 03:16:32,951 p=2253 u=shiyanlou |  TASK [echo success] ************************************************************
2019-10-24 03:16:33,279 p=2253 u=shiyanlou |  changed: [localhost]
2019-10-24 03:16:33,342 p=2253 u=shiyanlou |  TASK [debug] *******************************************************************
2019-10-24 03:16:33,427 p=2253 u=shiyanlou |  ok: [localhost] => {
    "msg": "root"
}
2019-10-24 03:16:33,441 p=2253 u=shiyanlou |  PLAY RECAP *********************************************************************
2019-10-24 03:16:33,441 p=2253 u=shiyanlou |  localhost                  : ok=3    changed=2    unreachable=0    failed=0   
2019-10-24 03:16:33,441 p=2253 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 1 seconds
2019-10-24 03:28:33,962 p=2348 u=shiyanlou |  PLAY [localhost] ***************************************************************
2019-10-24 03:28:34,032 p=2348 u=shiyanlou |  TASK [shell] *******************************************************************
2019-10-24 03:28:34,623 p=2348 u=shiyanlou |  changed: [localhost]
2019-10-24 03:28:34,624 p=2348 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (<ansible
.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackMo
dule object at 0x7f9d2f2e6ba8>): Error 111 connecting to 127.0.0.1:6379.
Connection refused.

2019-10-24 03:28:34,687 p=2348 u=shiyanlou |  TASK [echo success] ************************************************************
2019-10-24 03:28:35,013 p=2348 u=shiyanlou |  changed: [localhost]
2019-10-24 03:28:35,081 p=2348 u=shiyanlou |  TASK [debug] *******************************************************************
2019-10-24 03:28:35,131 p=2348 u=shiyanlou |  fatal: [localhost]: FAILED! => {"msg": "template error while templating string: expected token 'end of print statement', got 'b'. String: {{ s.stdout b.stdout }}"}
2019-10-24 03:28:35,132 p=2348 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ans
ible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.Callba
ckModule object at 0x7f9d2f2e6ba8>): Error 111 connecting to 127.0.0.1:6379.
Connection refused.

2019-10-24 03:28:35,146 p=2348 u=shiyanlou |  	to retry, use: --limit @/home/shiyanlou/.ansible-retry/sudo.retry

2019-10-24 03:28:35,146 p=2348 u=shiyanlou |  PLAY RECAP *********************************************************************
2019-10-24 03:28:35,146 p=2348 u=shiyanlou |  localhost                  : ok=2    changed=2    unreachable=0    failed=1   
2019-10-24 03:28:35,146 p=2348 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 1 seconds
2019-10-24 03:29:26,647 p=2434 u=shiyanlou |  PLAY [localhost] ***************************************************************
2019-10-24 03:29:26,712 p=2434 u=shiyanlou |  TASK [shell] *******************************************************************
2019-10-24 03:29:27,288 p=2434 u=shiyanlou |  changed: [localhost]
2019-10-24 03:29:27,289 p=2434 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (<ansible
.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackMo
dule object at 0x7f473781d978>): Error 111 connecting to 127.0.0.1:6379.
Connection refused.

2019-10-24 03:29:27,361 p=2434 u=shiyanlou |  TASK [echo success] ************************************************************
2019-10-24 03:29:27,693 p=2434 u=shiyanlou |  changed: [localhost]
2019-10-24 03:29:27,760 p=2434 u=shiyanlou |  TASK [debug] *******************************************************************
2019-10-24 03:29:27,842 p=2434 u=shiyanlou |  ok: [localhost] => {
    "msg": "total 32\n-rw-rw-r-- 1 shiyanlou shiyanlou  121 Oct 22 21:47 fetch.yml\n-rw-rw-r-- 1 shiyanlou shiyanlou  756 Oct 20 00:17 redis_opt.yml\n-rw-rw-r-- 1 shiyanlou shiyanlou  145 Oct 21 22:14 shell.yml\n-rw-rw-r-- 1 shiyanlou shiyanlou  238 Oct 24 03:29 sudo.yml\ndrwxrwxr-x 2 shiyanlou shiyanlou 4096 Oct 21 22:23 templates\n-rw-rw-r-- 1 shiyanlou shiyanlou  220 Oct 21 22:26 template.yml\n-rw-rw-r-- 1 shiyanlou shiyanlou   88 Oct 23 20:58 test_debug.yml\n-rw------- 1 shiyanlou shiyanlou   57 Oct 21 22:07 test.yml"
}
2019-10-24 03:29:27,851 p=2434 u=shiyanlou |  PLAY RECAP *********************************************************************
2019-10-24 03:29:27,851 p=2434 u=shiyanlou |  localhost                  : ok=3    changed=2    unreachable=0    failed=0   
2019-10-24 03:29:27,851 p=2434 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 1 seconds
2019-10-28 20:25:28,249 p=783 u=shiyanlou |  PLAY [localhost] **************************************************************************************************
2019-10-28 20:25:28,300 p=783 u=shiyanlou |  TASK [Gathering Facts] ********************************************************************************************
2019-10-28 20:25:32,447 p=783 u=shiyanlou |  ok: [localhost]
2019-10-28 20:25:32,511 p=783 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:25:32,571 p=783 u=shiyanlou |  skipping: [localhost] => (item=0) 
2019-10-28 20:25:32,586 p=783 u=shiyanlou |  skipping: [localhost] => (item=2) 
2019-10-28 20:25:32,597 p=783 u=shiyanlou |  skipping: [localhost] => (item=4) 
2019-10-28 20:25:33,204 p=783 u=shiyanlou |  changed: [localhost] => (item=6)
2019-10-28 20:25:33,484 p=783 u=shiyanlou |  changed: [localhost] => (item=8)
2019-10-28 20:25:33,766 p=783 u=shiyanlou |  changed: [localhost] => (item=10)
2019-10-28 20:25:33,768 p=783 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at
0x7ff88abf0b00>): Error 111 connecting to 127.0.0.1:6379. Connection refused.

2019-10-28 20:25:33,942 p=783 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:25:33,978 p=783 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_skipped) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at
0x7ff88abf0b00>): name 'host' is not defined

2019-10-28 20:25:34,032 p=783 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:25:34,151 p=783 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-28 20:25:34,151 p=783 u=shiyanlou |  localhost                  : ok=2    changed=1    unreachable=0    failed=0   
2019-10-28 20:25:34,152 p=783 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 6 seconds
2019-10-28 20:26:12,967 p=904 u=shiyanlou |  PLAY [localhost] **************************************************************************************************
2019-10-28 20:26:13,047 p=904 u=shiyanlou |  TASK [检查redis-server文件是否存在] ***************************************************************************************
2019-10-28 20:26:13,873 p=904 u=shiyanlou |  ok: [localhost]
2019-10-28 20:26:13,876 p=904 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at
0x7f0f6566db38>): Error 111 connecting to 127.0.0.1:6379. Connection refused.

2019-10-28 20:26:13,952 p=904 u=shiyanlou |  TASK [安装redis] ****************************************************************************************************
2019-10-28 20:26:14,001 p=904 u=shiyanlou |  skipping: [localhost]
2019-10-28 20:26:14,002 p=904 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_skipped) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at
0x7f0f6566db38>): name 'host' is not defined

2019-10-28 20:26:14,063 p=904 u=shiyanlou |  TASK [Redis配置文件] **************************************************************************************************
2019-10-28 20:26:15,263 p=904 u=shiyanlou |  ok: [localhost]
2019-10-28 20:26:15,325 p=904 u=shiyanlou |  TASK [检测Redis服务是否启动] **********************************************************************************************
2019-10-28 20:26:16,123 p=904 u=shiyanlou |  fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/bin/redis-cli quit", "delta": "0:00:00.154658", "end": "2019-10-28 20:26:16.071248", "msg": "non-zero return code", "rc": 1, "start": "2019-10-28 20:26:15.916590", "stderr": "Could not connect to Redis at 127.0.0.1:6379: Connection refused", "stderr_lines": ["Could not connect to Redis at 127.0.0.1:6379: Connection refused"], "stdout": "", "stdout_lines": []}
2019-10-28 20:26:16,123 p=904 u=shiyanlou |  ...ignoring
2019-10-28 20:26:16,124 p=904 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at
0x7f0f6566db38>): Error 111 connecting to 127.0.0.1:6379. Connection refused.

2019-10-28 20:26:16,182 p=904 u=shiyanlou |  TASK [启动Redis服务，如果redis 未启动] **************************************************************************************
2019-10-28 20:26:16,663 p=904 u=shiyanlou |  changed: [localhost]
2019-10-28 20:26:16,680 p=904 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-28 20:26:16,681 p=904 u=shiyanlou |  localhost                  : ok=4    changed=2    unreachable=0    failed=0   
2019-10-28 20:26:16,681 p=904 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 3 seconds
2019-10-28 20:26:25,341 p=1032 u=shiyanlou |  PLAY [localhost] **************************************************************************************************
2019-10-28 20:26:25,421 p=1032 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:26:25,469 p=1032 u=shiyanlou |  skipping: [localhost] => (item=0) 
2019-10-28 20:26:25,482 p=1032 u=shiyanlou |  skipping: [localhost] => (item=2) 
2019-10-28 20:26:25,506 p=1032 u=shiyanlou |  skipping: [localhost] => (item=4) 
2019-10-28 20:26:26,143 p=1032 u=shiyanlou |  changed: [localhost] => (item=6)
2019-10-28 20:26:26,461 p=1032 u=shiyanlou |  changed: [localhost] => (item=8)
2019-10-28 20:26:26,754 p=1032 u=shiyanlou |  changed: [localhost] => (item=10)
2019-10-28 20:26:26,825 p=1032 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:26:26,863 p=1032 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_skipped) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at
0x7f9686a33978>): name 'host' is not defined

2019-10-28 20:26:26,924 p=1032 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:26:27,001 p=1032 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-28 20:26:27,002 p=1032 u=shiyanlou |  localhost                  : ok=1    changed=1    unreachable=0    failed=0   
2019-10-28 20:26:27,002 p=1032 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 1 seconds
2019-10-28 20:32:50,385 p=1132 u=shiyanlou |  PLAY [localhost] **************************************************************************************************
2019-10-28 20:32:50,461 p=1132 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:32:50,516 p=1132 u=shiyanlou |  skipping: [localhost] => (item=0) 
2019-10-28 20:32:50,531 p=1132 u=shiyanlou |  skipping: [localhost] => (item=2) 
2019-10-28 20:32:50,541 p=1132 u=shiyanlou |  skipping: [localhost] => (item=4) 
2019-10-28 20:32:51,162 p=1132 u=shiyanlou |  changed: [localhost] => (item=6)
2019-10-28 20:32:51,441 p=1132 u=shiyanlou |  changed: [localhost] => (item=8)
2019-10-28 20:32:51,731 p=1132 u=shiyanlou |  changed: [localhost] => (item=10)
2019-10-28 20:32:51,791 p=1132 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:32:51,830 p=1132 u=shiyanlou |   [WARNING]: Failure using method (v2_runner_on_skipped) in callback plugin
(<ansible.plugins.callback./home/shiyanlou/ansible_ui/callback_plugins/redis2.CallbackModule object at
0x7ff3fc36a828>): name 'host' is not defined

2019-10-28 20:32:51,896 p=1132 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:32:51,966 p=1132 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-28 20:32:51,966 p=1132 u=shiyanlou |  localhost                  : ok=1    changed=1    unreachable=0    failed=0   
2019-10-28 20:32:51,966 p=1132 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 1 seconds
2019-10-28 20:34:47,501 p=1223 u=shiyanlou |  PLAY [localhost] **************************************************************************************************
2019-10-28 20:34:47,564 p=1223 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:34:47,619 p=1223 u=shiyanlou |  skipping: [localhost] => (item=0) 
2019-10-28 20:34:47,629 p=1223 u=shiyanlou |  skipping: [localhost] => (item=2) 
2019-10-28 20:34:47,647 p=1223 u=shiyanlou |  skipping: [localhost] => (item=4) 
2019-10-28 20:34:48,281 p=1223 u=shiyanlou |  changed: [localhost] => (item=6)
2019-10-28 20:34:49,551 p=1223 u=shiyanlou |  changed: [localhost] => (item=8)
2019-10-28 20:34:49,847 p=1223 u=shiyanlou |  changed: [localhost] => (item=10)
2019-10-28 20:34:49,904 p=1223 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:34:50,002 p=1223 u=shiyanlou |  TASK [command] ****************************************************************************************************
2019-10-28 20:34:50,080 p=1223 u=shiyanlou |  PLAY RECAP ********************************************************************************************************
2019-10-28 20:34:50,081 p=1223 u=shiyanlou |  localhost                  : ok=1    changed=1    unreachable=0    failed=0   
2019-10-28 20:34:50,081 p=1223 u=shiyanlou |  Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds
